version: '3'
services:
  main:
    build: EnergyPlusExample
    ports:
      - "5000:5000"
      - "5001:5001"
      - "1234:1234"
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./EnergyPlusExample:/app
