name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  test:
    name: Test on Ubuntu with Python 3.10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Downcase REPO
        run: |
          echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_OWNER }}/mostcool:latest
          build-args: |
            RUN_TESTS=true
          
      - name: Pull Docker image
        run: |
          docker pull ghcr.io/${{ env.REPO_OWNER }}/mostcool:latest

      - name: Remove existing Docker container
        run: |
          docker rm -f mostcool-container || true

      - name: Run tests inside Docker container
        run: |
          docker run --name mostcool-container-test --network host --env="DISPLAY=${DISPLAY}" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" ghcr.io/${{ env.REPO_OWNER }}/mostcool:latest pytest --cov=mostcool --cov-report=xml /app/mostcool/tests/

      - name: Copy coverage report from Docker container
        run: |
          docker cp mostcool-container-test:/app/mostcool/coverage.xml .

      - name: Stop and remove Docker container after running tests
        run: |
          docker stop mostcool-container-test
          docker rm mostcool-container-test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}